### ISSUE TITLE
The global http mixin in http_state is invalid with node trunk.

### ISSUE THREAD

**Issue by Nthalk** [gjritter/nerve#1]
---

```
Error:
```

---

TypeError: Object #<an IncomingMessage> has no method 'get_or_create_session'
    at Server.request_handler (/home/nthalk/.node_libraries/nerve.js:109:22)
    at EventEmitter.<anonymous> (/home/nthalk/.me/lib/node/libraries/http.js:411:23)
    at ServerSideConnection.<anonymous> (/home/nthalk/.me/lib/node/libraries/http.js:332:12)
    at node.js:995:9
TypeError: Object #<an IncomingMessage> has no method 'get_or_create_session'
    at Server.request_handler (/home/nthalk/.node_libraries/nerve.js:109:22)
    at EventEmitter.<anonymous> (/home/nthalk/.me/lib/node/libraries/http.js:411:23)
    at ServerSideConnection.<anonymous> (/home/nthalk/.me/lib/node/libraries/http.js:332:12)
    at node.js:995:9

---

```
Explanation:
```

---

It looks like module modification is parent down, not child up. So when you were including http_state and depending on it to modify the parent's http objects, it failed because that operation is no longer supported. See the Node.js section below.

---

```
Node.js:
```

---

commit b73f61a137841cebac8459203b6be3baa1756980
Author: Felix Geisendörfer felix@debuggable.com
Date:   Thu Feb 4 22:28:04 2010 +0100

```
Simplified module system

createModule got removed as it was unnecessary and caused issues by
doing its own cache checks independent of loadModule. Internal modules
are now the only globally cached modules, all other modules are only
cached by inheriting their parent modules cache.

Credits: Module specific cache and a few other diffs by Blaine Cook

http://github.com/blaine/node/commit/431662d25c0db3096deb5f679ca73b1dd6bb8ae
http://romeda.org/blog/2010/01/hot-code-loading-in-nodejs.html
http://thread.gmane.org/gmane.comp.lang.javascript.nodejs/1994
```

---

```
Patch:
```

---

commit d578284d8b10ebb41c4ffe19f3b8843914f3208e
Author: Carl Taylor <nthalk@orbital.(none)>
Date:   Sat Feb 6 23:36:42 2010 -0800

```
Updated to work with latest node.js where global imports seem to be isolated. reference: TypeError: Object #<an IncomingMessage> has no method 'get_or_create_session'
```

diff --git a/lib/http_state.js b/lib/http_state.js
index 1249c76..917fc3e 100644
--- a/lib/http_state.js
+++ b/lib/http_state.js
@@ -49,5 +49,11 @@
        }
    }
-   // Do cleanup
  setInterval(cleanup_sessions, 1000);
-   
-   // Export the data
-   for(n in http){
-       exports[n] = http[n];
-   }
  }());
  \ No newline at end of file
  diff --git a/lib/nerve.js b/lib/nerve.js
  index a57d5ad..c821890 100644
  --- a/lib/nerve.js
  +++ b/lib/nerve.js
  @@ -3,12 +3,12 @@
  
  (function () {
    var sys = require('sys'),
-       http = require('http'),
-       http = require('./http_state'),
      url = require('url'),
      path = require('path'),
      posix = require('posix'),
      mime = require('./mime');
-   require('./http_state');
-   ;
  
  process.mixin(http.ServerResponse.prototype, {
      respond: function (response_data) {

**Comment by gjritter** [comment]
Fixed in 3fa228c. Thanks for reporting the issue!
