### ISSUE TITLE
redirect support

### ISSUE THREAD

**Issue by drjohn** [gjritter/nerve#3]
need to have support for redirect  something like:  redirect("/home")

**Comment by gjritter** [comment]
I'm working on some changes to nerve that will provide support for forwarding requests from one handler to another, without needing to do an HTTP redirect.

Do you need HTTP redirects (http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3) as well? If so, those can already be accomplished by sending appropriately coded responses (HTTP status codes 3xx), although I could perhaps add syntactic sugar for sending such responses.

**Comment by drjohn** [comment]
yes, I think both are needed - sometimes going to a completely different site - sometimes (probably most times) going right back to the app controller something like redirect ('/login')
